version: "3.8"
services:
    dev-db:
        image: postgres
        container_name: opencsdb
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
